version: "3"


services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    ports:
#      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: portainer
    restart: unless-stopped


volumes:
  portainer_data:
